site_name: EPITECH Documentation
repo_url: https://github.com/epitools2024/epitech-documentation.git
site_description: "All you will use at EPITECH"
site_author: epitools2024

theme:
    name: windmill
    colorscheme: github
    shortcuts:
        next: 78
        previous: 80
        search: 83

nav:
    - ABOUT EPITECH:
        - Epitech PEDAGOGY: about_epitech/epitech.md
        - Links & Documents: about_epitech/links_docs.md
    - INSTALLATION & CONFIGURATIONS:
        - Windows + Linux Distro: install_config/dual_boot.md
        - EPITECH DUMP: install_config/dump.md
    - TOOLS CHEATSHEET:
        - Blih: tools_cheatsheet/blih.md
        - Emacs: tools_cheatsheet/emacs.md
        - Git: tools_cheatsheet/git.md
        - Makefile: tools_cheatsheet/makefile.md
        - Csfml Library: tools_cheatsheet/csfml.md
        - Ncurses Library: tools_cheatsheet/ncurses.md
    - C PROGRAMMING:
        - Simples functions: c_programming/functions.md
        - Your library: c_programming/libmy.md
        - Unit Test: c_programming/unit_test.md
    - ABOUT US:
        - EPITOOLS: about_us/epitools.md
        - Contribution: about_us/contribution.md
        - LICENSE: about_us/license.md

markdown_extensions:
    - toc:
        baselevel: 2

copyright: EPITOOLS 2024